Make a note editable
turingschool-projects/1610-remember-7 pull request #16
Opened 2017-02-15 21:21 UTC by apsitos

Closes #15 and #3 

## Purpose

When viewing an existing reminder, the user can click on an “Edit” button where they can modify the title, notes, or date of the reminder.

## Approach

If you make a typo or use bad grammar, you can now fix it! Though if you’re the only one seeing the reminder, maybe you don’t care. 

### Learning

We did a lot of research that wasn’t super helpful. We had to screenhero with Brenna twice to get this working because Ember is stupid.

We read about the [mutable](http://emberjs.com/api/classes/Ember.Templates.helpers.html#method_mut) property, but didn’t end up using it.
 
#### Blog Posts

### Open Questions and Pre-Merge TODOs

- [x] When editing a note, there is a “Save” button that commits the changes to the server.
- [x] When the user hits the save button, they are returned to the original individual note path (ie: reminders/1).

### Test coverage 

Wrote two tests: one checks that the edit button re-routes to the edit page, the second tests that we can mutate the title field and save the new text.

### Merge Dependencies and Related Work

### Follow-up tasks

- [Issue #9](https://github.com/turingschool-projects/1610-remember-7/issues/9)

### Screenshots

#### Before

#### After

2017-02-15 21:54 UTC, martensonbj requested changes
Hey - question about the communication between your component and route situation - Also there are merge conflicts. REsolve those please and then repush and we'll dig back in :)

2017-02-15 21:54 UTC, martensonbj commented on app/routes/edit.js
> +      this.transitionTo("/reminders")
Is this firing? You might need a `sendAction()` line in your component.

2017-02-15 22:12 UTC, JeffBuss commented on app/routes/edit.js
> +      this.transitionTo("/reminders")
It isn't, and is completely unnecessary at this point. We had originally tried handling it in the route, but instead used a link in the edit-reminder component. Good eyes!

2017-02-15 22:15 UTC, JeffBuss commented
@martensonbj requested changes complete!

2017-02-15 23:39 UTC, martensonbj requested changes
Few more things! Thanks for the effort guys :)

2017-02-15 23:39 UTC, martensonbj commented on tests/unit/controllers/edit-test.js
> +import { moduleFor, test } from 'ember-qunit';
Get rid of this file yo!

2017-02-15 23:39 UTC, martensonbj commented on tests/acceptance/reminder-list-test.js
>    click('button');
What button? Add a class here or at least a button with a particular text

2017-02-15 23:39 UTC, martensonbj commented on tests/acceptance/reminder-list-test.js
> +test('editing notes', function(assert) {
Let's set a variable to whatever the title is first, and check that the edited title is different. Right now it just asserts that whatever you typed matches what you typed.

2017-02-16 04:59 UTC, apsitos commented
@martensonbj Changes made!

2017-02-16 16:16 UTC, martensonbj approved these changes

2017-02-16 16:17 UTC, merged